### ISSUE TITLE
Openlayers 7 support?

### ISSUE THREAD

**Issue by jaakko-solita** [ghettovoice/ol3-rotate-feature#22]
We have been using this with OL 7.4.0 and it seems to work fine

However `yarn install` complains:
`warning " > ol-rotate-feature@3.0.1" has incorrect peer dependency "ol@^6.0.0".`

Could the peer dependencies be updated?

**Comment by ghettovoice** [comment]
Hello @jaakko-solita ,
ok, thanks for info.
I will check tests, api and update

**Comment by ghettovoice** [comment]
Seems working well, the version is bumped

**Comment by digoburigo** [comment]
```bash
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "^6.0.0|^7.0.0" of package "ol@^6.0.0|^7.0.0": Tags may not have any characters that encodeURIComponent encodes.
```

getting this error when trying to upgrade
