### ISSUE TITLE
Upgrade to ol 8

### ISSUE THREAD

**Issue by vojtech-osvald** [ghettovoice/ol3-rotate-feature#25]
Hello,
please make changes to support openlayers 8.

I created a pull request (https://github.com/ghettovoice/ol-rotate-feature/pull/24) that should do the trick.

Thanks, Vojtech Osvald

**Comment by ghettovoice** [comment]
Hello @vojtech-osvald ,
thanks for contribution!

Let some time to review and publish

**Comment by vojtech-osvald** [comment]
Thank you for the merge.

However, the change in imports was an important part of the commit. When you reverted it via commit b845fd9ab09b24c3c812994803e77c26b79710a0, you made the package not usable again. At least in my case, where I, in one project, import ol 8.2.0 and also ol-rotate-feature 3.2.0. The project cannot be built with errors from ol-rotate-feature library:

![image](https://github.com/ghettovoice/ol-rotate-feature/assets/52031491/fa23eaa3-8472-49c8-b82a-037e6c8af415)

Can you please revalidate the reversive commit?

(similar issue, a little bit old, is being discussed here https://github.com/geotiffjs/geotiff.js/issues/254#issuecomment-940962109)

Thanks, Vojtech

**Comment by ghettovoice** [comment]
@vojtech-osvald sorry, didn't know about this.
new v3.2.1 with direct source import is released.

**Comment by vojtech-osvald** [comment]
Thank you, version 3.2.1 works flawlessly.

**Comment by jdewilde** [comment]
And openlayers 9.x?

**Comment by ghettovoice** [comment]
@jdewilde , I need to check that 9.x is working too 

UPD: seems it is compatible without any changes, going to upgrade and release...
