### ISSUE TITLE
Demo does not work

### ISSUE THREAD

**Issue by MUYUM** [ghettovoice/ol3-rotate-feature#26]
Demo site does not work: https://ghettovoice.github.io/ol-rotate-feature/demo.html

It seems, that there is a problem with loading `OL.js` and `OL.css`, which relates to [this issue](https://github.com/openlayers/openlayers.github.io/issues/113).

Please update and reference to the new packages:
https://cdnjs.cloudflare.com/ajax/libs/openlayers/9.1.0/dist/ol.min.js
https://cdnjs.cloudflare.com/ajax/libs/openlayers/9.1.0/ol.css

**Comment by ghettovoice** [comment]
Thanks @MUYUM

**Comment by MUYUM** [comment]
No worries. Tested, and everything is working as expected. Thanks.
