### ISSUE TITLE
Open Layers 4 support?

### ISSUE THREAD

**Issue by itsonit** [ghettovoice/ol3-rotate-feature#3]
I tried the plugin with OL4 - is Open Layers 4 supported or did I miss something?

see: https://codepen.io/itsonit/pen/KZeqBq

**Comment by ghettovoice** [comment]
Hi! It seems that something has changed in OpenLayers interaction API. I'll check this soon.
Thank you!

**Comment by ghettovoice** [comment]
Did not notice that you forgot add `select` and `rotate` instances to map, add to the end and all should work as expected:
```
map.addInteraction(select)
map.addInteraction(rotate)
```

**Comment by itsonit** [comment]
Sorry for the noise. Everything works as expected. ty!
