### ISSUE TITLE
Prevent anchor from moving?

### ISSUE THREAD

**Issue by ablakey** [ghettovoice/ol3-rotate-feature#4]
I'm looking at the demo and am curious if you're able to disallow movement of the anchor. Ie. I want the anchor to begin at the 0,0 of the feature and not be movable.

Thanks.

P.S. this ol Interaction is fantastic. Thank you for authoring it!

**Comment by ghettovoice** [comment]
Hi! Currently interaction not able to fix anchor at some coordinate. 
I plan to add several properties something like `moveAnhorCondition`, `rotateFeatureCondition`, like in [ol.interaction.Draw](https://openlayers.org/en/latest/apidoc/ol.interaction.Draw.html) or [ol.interaction.Modify](https://openlayers.org/en/latest/apidoc/ol.interaction.Modify.html).
But I haven't a lot of time right now to do it. Contributing are welcome

**Comment by ablakey** [comment]
Thanks for letting me know.  I likely need this in the next few weeks, so you are likely to see a PR from me presenting a possible way to address this option.

**Comment by ghettovoice** [comment]
Ok, thank you!

**Comment by ablakey** [comment]
A quick follow-up for anyone else who finds this.

You can easily disable the anchor from moving function by simply passing the interaction a set of styles that does not contain an anchor style. This means that there's no anchor to click on and therefore no way to move it.

This is kinda kludgy but it works!

**Comment by ghettovoice** [comment]
Thank you for your investigation! The solution was on the surface, I didn't thinks about `style` property.
