### ISSUE TITLE
Open Layers 5 support?

### ISSUE THREAD

**Issue by digoburigo** [ghettovoice/ol3-rotate-feature#6]
With the arrival of the new version (5.0.0), i want to know if its going to be updated or if works normally? Thanks

**Comment by ghettovoice** [comment]
Hi @digoburigo ,
probably it  will not work due to changes in path and may be in interaction api.
I need to investigate this.
Thank you

**Comment by ghettovoice** [comment]
Starting from [v2](https://www.npmjs.com/package/ol-rotate-feature) ol-rotate-feature now supports ol v5.
Please check

**Comment by digoburigo** [comment]
Hello, i checked and it works. Congratulations for your work. And thank you for your time to upgrade this awesome plugin.
