### ISSUE TITLE
Problem with OpenLayers 5.3 with Angular 7.0.3

### ISSUE THREAD

**Issue by digoburigo** [ghettovoice/ol3-rotate-feature#7]
When using the last update (5.3) of OpenLayers with Angular 7.0.3 this warning is shown when serving the app:
``` 
WARNING in ./node_modules/ol-rotate-feature/dist/bundle.es.js 760:9-20
"export 'handleEvent' was not found in 'ol/interaction/Pointer'
i ｢wdm｣: Compiled with warnings.
```
That causes this error when trying to rotate a feature in the application:
``` 
ERROR TypeError: Cannot read property 'call' of undefined
    at RotateFeatureInteraction.handleEvent$1 [as handleEvent]
...
```

**Comment by ghettovoice** [comment]
Hi @digoburigo ,
thanks for report. I already have another report about this problem. 

I'll check openlayers changelog, obviously something was changed in interaction api.

**Comment by ghettovoice** [comment]
Please try with the new version v2.0.1

**Comment by digoburigo** [comment]
I tried and its working again, thanks for your time.
