### ISSUE TITLE
Example to overrule styles

### ISSUE THREAD

**Issue by Nic2012** [ghettovoice/ol3-rotate-feature#8]
Hi,
happy new year and thank you providing us this ol-interaction :)
Could y give us an example how we can overrule css styles to hide the anchor icon for example or setting font color to the caption showing current angle on map?

Thx and best regards,
Nic

**Comment by ghettovoice** [comment]
Hi @Nic2012,
sorry for the late response. Happy new year you too!
Take a look here https://jsfiddle.net/ghettovoice/d4e0m8tq/. It is example from demo a little bit changed.

RotateFeature interaction has the options `style` which can be used to provide custom style function for interaction internal overlay. Inside the style function you can check two feature properties: 
- rotate-anchor - will be true if the feature is an anchor
- rotate-arrow - will be true if the feature is an arrow
